In [ ]:
import numpy as np
#Creating arrays
arr=np.array([1,2,3,4,5],dtype=float)
print(arr)

[1. 2. 3. 4. 5.]


In [ ]:
zeros_arr=np.zeros((3,3),dtype=float)
print(zeros_arr)
ones_arr=np.ones((2,2),dtype=int)
print(ones_arr)
arange_arr=np.arange(10)
print(arange_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1 1]
 [1 1]]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#Array Manipulation
reshaped_arr=arr.reshape(5,1)
print(reshaped_arr)
#slicing the array
sliced_array=arr[2:4]
print(sliced_array)
#transpose of the array
a=np.array([1,2,3,4,5,6])
b=a.T
print(b)
#split function
b=np.split(a,3)
print(b)
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.dot(a,b)
print(c)
d=np.linalg.eig(c)
print(d)

[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]
[3. 4.]
[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
[[19 22]
 [43 50]]
EigResult(eigenvalues=array([5.80198014e-02, 6.89419802e+01]), eigenvectors=array([[-0.75781077, -0.40313049],
       [ 0.65247439, -0.91514251]]))


In [ ]:
#Creating a text document
data=np.loadtxt("/content/drive/MyDrive/dataset/Dap.txt",dtype=int)
print(data)
d=np.savetxt("/content/hi.txt", data)
print(d)


[1 2 3 4 5]
None


In [ ]:
arange_arr=np.arange(0,100,5)
print(arange_arr)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [ ]:
a=np.random.rand()
print(a)
b=np.random.randint(0,2)
print(b)
a=np.array([[1,2],[3,4]])
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
a=np.linspace(0.8,2,5)
print(a)

0.8827302608366983
1
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
2
(2, 2)
[0.8 1.1 1.4 1.7 2. ]


In [ ]:
c=np.arange(0,5)
print(c)
c=np.arange(24).reshape(3,2,4)
print(c)

[0 1 2 3 4]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a*b)
print(a@b)
c=np.dot(a,b)
print(c)

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [ ]:
from numpy import random
a=np.ones((2,3),dtype=int)
print(a)
c=a.sum()
print(c)
print(a.sum(axis=1))#row wise
print(a.sum(axis=0))#column wise addition
a=np.floor(np.random.random((2,2)))
print(a)
c=np.random.random((2,12))
print(c.shape)
print(c)
a=np.ceil(np.random.random((2,12)))
print(a)
print(a.max())
print(a.max(axis=1))
d=np.array([[2,3],[4,5]])
print(a.max())
print(d.max())
print(d.cumsum(axis=1))
print(d.cumsum(axis=0))
a=np.array([2,3,5,6])
print(a.cumsum())
a=np.array([1,2,3,4,5,6])
print(a.resize(3,2))
print(a)
print(a.shape)
a=np.array([1,2,3,4,5,6])
a.resize(2,3)
b=np.array([7,8,9,10,11,12])
b.resize(2,3)
print(np.vstack((a,b)))
print(np.hstack((a,b)))
c=np.arange(30).reshape(2,3,5)
print(c)
print(np.dstack(a))

[[1 1 1]
 [1 1 1]]
6
[3 3]
[2 2 2]
[[0. 0.]
 [0. 0.]]
(2, 12)
[[0.11758425 0.38060096 0.49011748 0.24137768 0.85315842 0.13103157
  0.38652356 0.83686568 0.63928568 0.56216271 0.96720709 0.26398393]
 [0.27661098 0.15320532 0.26003024 0.7923643  0.96192091 0.0276026
  0.99078624 0.16606831 0.70472689 0.05733949 0.27473417 0.66615687]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
1.0
[1. 1.]
1.0
5
[[2 5]
 [4 9]]
[[2 3]
 [6 8]]
[ 2  5 10 16]
None
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
[[[1 4]
  [2 5]
  [3 6]]]


Number if rows become no.of group
Column become rows group become column

In [ ]:
#Arthemetic Operators
a=5
b=10
print(a==b)
print(a+b)
print(a//b)
print(a%b)
print(a/b)

False
15
0
5
0.5


In [ ]:
#Logical Operators
a=True
b=True
print(a&b)
print(a|b)
print(a and b)
print(a or b)
b=False
print(a&b)
print(a|b)
print(a and b)
print(a or b)

True
True
True
True
False
True
False
True


In [ ]:
#Relational Operators
a=7
b=5
print(a>b)
print(a<b)
print(a==b)
print(a<=b)
print(a>=b)


True
False
False
False
True


In [ ]:
n=10
for i in range(n):
  print(i)
for i in range(1,n+1):
    print(i)

0
1
2
3
4
5
6
7
8
9
1
2
3
4
5
6
7
8
9
10


In [ ]:
def prime(n):
  count=0
  for i in range(1,n+1):
    if i%n:
      count=count+1
  if count==2:
    print(i)

n=10
prime(n)

24-02-2024 Saturday

In [ ]:
a1=np.eye(4)
print(a1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
a1=np.full((2,2),3)
print(a1)
print(a1.itemsize)

[[3 3]
 [3 3]]
8


In [ ]:
x=[1,2,3,]
a=np.asarray(x)
print(a)
print(type(a))
x=np.array([1,4,0],float)
y=np.array([2,2,1],float)
print(np.inner(x,y))
print(np.outer(x,y))
print(np.cross(x,y))

[1 2 3]
<class 'numpy.ndarray'>
10.0
[[2. 2. 1.]
 [8. 8. 4.]
 [0. 0. 0.]]
[ 4. -1. -6.]


In [ ]:
x=np.array([1.1,2.2,3.3,4.4,5.5,6.6,7.7])
np.rint(x)

array([1., 2., 3., 4., 6., 7., 8.])

In [ ]:
a=np.array([10,15,20])
b=np.array([2,3,4])
np.true_divide(a,b)

array([5., 5., 5.])

In [ ]:
a=np.array([1,1,2,2,3,3,4,4])
print(np.unique(a))
b=np.array([[1,2],[3,3]])
c=np.array([[1,4],[4,7]])
print(np.union1d(b,c))
print(np.intersect1d(b,c))
np.setdiff1d(b,c)

[1 2 3 4]
[1 2 3 4 7]
[1]


array([2, 3])

In [ ]:
a=8
b=6
c=np.hypot(a,b)#hypotesis=root(a sqaure +b sqaure)
print(c)
x=np.sin(0)
print(x)
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
print(np.divmod(a,b))
print(np.divide(a,b))

10.0
0.0
(array([ 0,  1, 15,  2,  2,  2]), array([10,  0,  0,  0,  0, 10]))
[ 0.5  1.  15.   2.   2.   2.4]


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
print(np.multiply(a,b))

[ 200  441   60  800 1250 1500]


In [ ]:
from numpy import random
x=random.normal(size=(2,3))
print(x)
x=random.normal(loc=1,scale=2,size=(2,3))#loc=mean valu,scale=standard deviation
print(x)
x=random.binomial(n=12,p=0.5,size=10)#n=no.of trails,p=probability
print(x)
x=random.poisson(lam=2,size=10)
print(x)
x=random.choice([1,2,3,4,5])
print(x)
x=random.choice([3,5],p=[0.5,0.5],size=(3,5))
print(x)

[[-2.38448013 -1.14507298 -0.70372667]
 [-0.09248292  1.37411037  1.43367754]]
[[ 0.16674659  0.27078885 -0.80276349]
 [-0.81913764 -1.01448372  3.24196562]]
[5 7 7 8 6 5 7 7 8 3]
[0 1 0 0 1 1 3 3 0 1]
2
[[5 5 5 5 5]
 [5 3 3 3 5]
 [5 5 3 5 3]]
